/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORT2_15 (number 36), INT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_INT_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_INT_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LCD_INT_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_INT_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_INT_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_INT_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_22 (number 53), BLK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_BLK_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_BLK_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LCD_BLK_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LCD_BLK_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_BLK_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_BLK_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_BLK_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_0 (number 73), RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_RST_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_RST_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LCD_RST_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LCD_RST_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_RST_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_RST_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_RST_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_17 (number 38), DC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_DC_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_DC_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LCD_DC_GPIO_PIN 17U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LCD_DC_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_DC_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_DC_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_DC_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_19 (number 39), CS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_CS_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_CS_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LCD_CS_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LCD_CS_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_CS_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_CS_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_CS_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_23 (number 42), WR
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_WR_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_WR_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_WR_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_20 (number 40), RD
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_RD_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_RD_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_RD_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_21 (number 41), TE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_TE_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_TE_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LCD_TE_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_TE_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_TE_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_TE_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
