/**
 * @file    eeprom_interna_lpc40xx.c
 * @brief   Funciones para acceder a la EEPROM interna del LPC40xx.
 *
 * @author  Alejandro Lara Doña - alejandro.lara@uca.es
 * @date    2025
 * @version 1.0
 *
 * @copyright   GNU General Public License version 3 or later
 *
 */

#include "eeprom_interna_lpc40xx.h"
#include <LPC407x_8x_177x_8x.h>
#include "tipos.h"
#include "error.h"
#include "gpio_lpc40xx.h"
#include "timer_lpc40xx.h"

/**
 * @brief   Inicializa la comunicación SPI entre el uC y la memoria 25LC160.
 * @ingroup EEPROM Interna
 *
 * @details Se configuran los registros de divisor de reloj y los ciclos de espera de acuerdo con
 * el manual de usuario (pág. 870). Hay una errata
 *
 * Registro WSTATE
 *
 * Bits  | Símbolo | Formula
 * :---: | :-----: | :----------------
 * 7:0   | PHASE3  | (15ns * cclk) - 1
 * 15:8  | PHASE2  | (55ns * cclk) - 1
 * 23:16 | PHASE1  | (35ns * cclk) - 1
 *
 * Registro CLKDIV
 * 
 * $f[
 *   CLKDIV = \frac{CCLK}{375 kHz} - 1
 * $f]
 *
 * @warning Es necesario configurar correctamente el registro WSTATE y CLKDIV de acuerdo a la
 * frecuencia a la que se ejecute la CPU.
 */
void eeprom_interna_inicializar(void) {
  
  uint32_t wstate;
  /* Después del reset la EEPROM siempre está encendida, pero deshabilitamos el power-down por si 
   * algúna otra función lo activó antes.
   */
  LPC_EEPROM->PWRDWN = 0x0;
  /* Setting clock:
   * EEPROM required a 375kHz. This clock is generated by dividing the
   * system bus clock.
   */
  
  LPC_EEPROM->CLKDIV = SystemCoreClock / 375e3 - 1;

  // Calculamos el valor de los ciclos de espera
  wstate  =  (SystemCoreClock * 15) / 1000000000 + 1;
  wstate |= ((SystemCoreClock * 15) / 1000000000 + 1) << 8;
  wstate |= ((SystemCoreClock * 15) / 1000000000 + 1) << 16;
  
  LPC_EEPROM->WSTATE = wstate;
}

/**
 * @brief   Comprobar si en este momento hay una escritura en curso.
 * @ingroup EEPROM Interna
 *
 * @retval  TRUE => hay una escritura en curso.
 * @retval  FALSE => no hay una escritura en curso.
 */
bool_t eeprom_interna_escritura_en_curso(void) {
  // Retornar TRUE o FALSE según el bit END_OF_RW (bit 26) del registro de estado esté a 1 o a 0.
  return (LPC_EEPROM->INT_STATUS & EEPROM_END_OF_RW) == 0;
}

/**
 * @brief   Comprobar si en este momento está la programación en curso.
 * @ingroup EEPROM Interna
 *
 * @retval  TRUE => hay una programación en curso.
 * @retval  FALSE => no hay una programación en curso.
 */
bool_t eeprom_interna_programacion_en_curso(void) {
  // Retornar TRUE o FALSE según el bit EEPROM_END_OF_PROG (bit 28) del registro de estado esté a 1 o a 0.
  return (LPC_EEPROM->INT_STATUS & EEPROM_END_OF_PROG) == 0;
}

/**
 * @brief   Limpia el bit de escritura en curso.
 * @ingroup EEPROM Interna
 */
void eeprom_interna_limpiar_escritura_en_curso(void) {
  LPC_EEPROM->INT_CLR_STATUS = EEPROM_END_OF_RW;
}

/**
 * @brief   Limpia el bit de programación en curso.
 * @ingroup EEPROM Interna
 */
void eeprom_interna_limpiar_programacion_en_curso(void) {
  LPC_EEPROM->INT_CLR_STATUS = EEPROM_END_OF_PROG;
}

/**
 * @brief   Lee un byte de la EEPROM 25LC160.
 * @ingroup EEPROM Interna
 *
 * @param[in]   direccion   Dirección de la EEPROM que se quiere leer. Debe estar entre 0 y 4095.
 *
 * @return      Byte leído.
 */
uint32_t eeprom_interna_leer_dato(uint16_t direccion, eeprom_interna_bits_dato tam) {

  uint8_t d;

  /* Comprobar que la dirección está en el rango de 0 a 4095. Si no es así, abortar el programa
   * (usa la macro ASSERT de error.h).
   */
  ASSERT(direccion < 4096, "La dirección debe estar entre 0 y 0xFFF");

  // Esperar mientras haya una escritura en curso en la EEPROM
  while (eeprom_interna_escritura_en_curso()) {;}

    
  // Retornar el byte leído
  return d;
}

/**
 * @brief   Escribe un byte en la EEPROM 25LC160.
 * @ingroup EEPROM Interna
 *
 * @param[in]   direccion   Dirección de la EEPROM donde se quiere escribir. Debe estar entre
                            0 y 4095.
 * @param[in]   byte        Byte que se quiere escribir.
 */
void eeprom_interna_escribir_dato(uint16_t direccion, eeprom_interna_bits_dato tam, uint32_t dato) {

  /* Comprobar que la dirección está en el rango de 0 a 4095. Si no es así, abortar el programa
   * (usa la macro ASSERT de error.h).
   */
  ASSERT(direccion < 4096, "La dirección debe estar entre 0 y 0xFFF");

  // Esperar mientras haya una escritura en curso en la EEPROM.
  while (eeprom_interna_escritura_en_curso()) {;}

  /* Enviar el comando de habilitación de escritura realizando los pasos
   * del cronograma "Write enable sequence" del datasheet.
   */

}
