/**
 * @file    sonido_mario.h
 * @brief   Melodía del juego Super Mario Bros.
 *
 * @author  Alejandro Lara Doña - alejandro.lara@uca.es
 * @date    2026
 * @version 2.0
 *
 * @copyright GNU General Public License version 3 or later
 */

#ifndef SONIDO_MARIO_H
#define SONIDO_MARIO_H

#include "tipos.h"
#include "sonido.h"

const uint16_t mario_theme_notes[] = {

  // Super Mario Bros theme
  // Score available at https://musescore.com/user/2123/scores/2145
  // Theme by Koji Kondo

  SONIDO_NOTA_E5, SONIDO_NOTA_E5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_E5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_C5, SONIDO_NOTA_E5, //1
  SONIDO_NOTA_G5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA,
  SONIDO_NOTA_C5, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_E4, // 3
  SONIDO_NOTA_A4, SONIDO_NOTA_B4, SONIDO_NOTA_AS4, SONIDO_NOTA_A4,
  SONIDO_NOTA_G4, SONIDO_NOTA_E5, SONIDO_NOTA_G5, SONIDO_NOTA_A5, SONIDO_NOTA_F5, SONIDO_NOTA_G5,
  SONIDO_NOTA_PAUSA, SONIDO_NOTA_E5,SONIDO_NOTA_C5, SONIDO_NOTA_D5, SONIDO_NOTA_B4,
  SONIDO_NOTA_C5, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_E4, // repeats from 3
  SONIDO_NOTA_A4, SONIDO_NOTA_B4, SONIDO_NOTA_AS4, SONIDO_NOTA_A4,
  SONIDO_NOTA_G4, SONIDO_NOTA_E5, SONIDO_NOTA_G5, SONIDO_NOTA_A5, SONIDO_NOTA_F5, SONIDO_NOTA_G5,
  SONIDO_NOTA_PAUSA, SONIDO_NOTA_E5,SONIDO_NOTA_C5, SONIDO_NOTA_D5, SONIDO_NOTA_B4,


  SONIDO_NOTA_PAUSA, SONIDO_NOTA_G5, SONIDO_NOTA_FS5, SONIDO_NOTA_F5, SONIDO_NOTA_DS5, SONIDO_NOTA_E5,//7
  SONIDO_NOTA_PAUSA, SONIDO_NOTA_GS4, SONIDO_NOTA_A4, SONIDO_NOTA_C4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_A4, SONIDO_NOTA_C5, SONIDO_NOTA_D5,
  SONIDO_NOTA_PAUSA, SONIDO_NOTA_DS5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_D5,
  SONIDO_NOTA_C5, SONIDO_NOTA_PAUSA,

  SONIDO_NOTA_PAUSA, SONIDO_NOTA_G5, SONIDO_NOTA_FS5, SONIDO_NOTA_F5, SONIDO_NOTA_DS5, SONIDO_NOTA_E5,//repeats from 7
  SONIDO_NOTA_PAUSA, SONIDO_NOTA_GS4, SONIDO_NOTA_A4, SONIDO_NOTA_C4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_A4, SONIDO_NOTA_C5, SONIDO_NOTA_D5,
  SONIDO_NOTA_PAUSA, SONIDO_NOTA_DS5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_D5,
  SONIDO_NOTA_C5, SONIDO_NOTA_PAUSA,

  SONIDO_NOTA_C5, SONIDO_NOTA_C5, SONIDO_NOTA_C5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_C5, SONIDO_NOTA_D5,//11
  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_A4, SONIDO_NOTA_G4,

  SONIDO_NOTA_C5, SONIDO_NOTA_C5, SONIDO_NOTA_C5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_C5, SONIDO_NOTA_D5, SONIDO_NOTA_E5,//13
  SONIDO_NOTA_PAUSA,
  SONIDO_NOTA_C5, SONIDO_NOTA_C5, SONIDO_NOTA_C5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_C5, SONIDO_NOTA_D5,
  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_A4, SONIDO_NOTA_G4,
  SONIDO_NOTA_E5, SONIDO_NOTA_E5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_E5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_C5, SONIDO_NOTA_E5,
  SONIDO_NOTA_G5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA,
  SONIDO_NOTA_C5, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_E4, // 19

  SONIDO_NOTA_A4, SONIDO_NOTA_B4, SONIDO_NOTA_AS4, SONIDO_NOTA_A4,
  SONIDO_NOTA_G4, SONIDO_NOTA_E5, SONIDO_NOTA_G5, SONIDO_NOTA_A5, SONIDO_NOTA_F5, SONIDO_NOTA_G5,
  SONIDO_NOTA_PAUSA, SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_D5, SONIDO_NOTA_B4,

  SONIDO_NOTA_C5, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_E4, // repeats from 19
  SONIDO_NOTA_A4, SONIDO_NOTA_B4, SONIDO_NOTA_AS4, SONIDO_NOTA_A4,
  SONIDO_NOTA_G4, SONIDO_NOTA_E5, SONIDO_NOTA_G5, SONIDO_NOTA_A5, SONIDO_NOTA_F5, SONIDO_NOTA_G5,
  SONIDO_NOTA_PAUSA, SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_D5, SONIDO_NOTA_B4,

  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_GS4,//23
  SONIDO_NOTA_A4, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_A4,
  SONIDO_NOTA_D5, SONIDO_NOTA_A5, SONIDO_NOTA_A5, SONIDO_NOTA_A5, SONIDO_NOTA_G5, SONIDO_NOTA_F5,

  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_A4, SONIDO_NOTA_G4, //26
  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_GS4,
  SONIDO_NOTA_A4, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_A4,
  SONIDO_NOTA_B4, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_E5, SONIDO_NOTA_D5,
  SONIDO_NOTA_C5, SONIDO_NOTA_E4, SONIDO_NOTA_E4, SONIDO_NOTA_C4,

  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_GS4,//repeats from 23
  SONIDO_NOTA_A4, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_A4,
  SONIDO_NOTA_D5, SONIDO_NOTA_A5, SONIDO_NOTA_A5, SONIDO_NOTA_A5, SONIDO_NOTA_G5, SONIDO_NOTA_F5,

  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_A4, SONIDO_NOTA_G4, //26
  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_GS4,
  SONIDO_NOTA_A4, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_A4,
  SONIDO_NOTA_B4, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_E5, SONIDO_NOTA_D5,
  SONIDO_NOTA_C5, SONIDO_NOTA_E4, SONIDO_NOTA_E4, SONIDO_NOTA_C4,
  SONIDO_NOTA_C5, SONIDO_NOTA_C5, SONIDO_NOTA_C5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_C5, SONIDO_NOTA_D5, SONIDO_NOTA_E5,
  SONIDO_NOTA_PAUSA,

  SONIDO_NOTA_C5, SONIDO_NOTA_C5, SONIDO_NOTA_C5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_C5, SONIDO_NOTA_D5, //33
  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_A4, SONIDO_NOTA_G4,
  SONIDO_NOTA_E5, SONIDO_NOTA_E5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_E5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_C5, SONIDO_NOTA_E5,
  SONIDO_NOTA_G5, SONIDO_NOTA_PAUSA, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA,
  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_GS4,
  SONIDO_NOTA_A4, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_A4,
  SONIDO_NOTA_D5, SONIDO_NOTA_A5, SONIDO_NOTA_A5, SONIDO_NOTA_A5, SONIDO_NOTA_G5, SONIDO_NOTA_F5,

  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_A4, SONIDO_NOTA_G4, //40
  SONIDO_NOTA_E5, SONIDO_NOTA_C5, SONIDO_NOTA_G4, SONIDO_NOTA_PAUSA, SONIDO_NOTA_GS4,
  SONIDO_NOTA_A4, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_A4,
  SONIDO_NOTA_B4, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_F5, SONIDO_NOTA_E5, SONIDO_NOTA_D5,
  SONIDO_NOTA_C5, SONIDO_NOTA_E4, SONIDO_NOTA_E4, SONIDO_NOTA_C4,

  //game over sound
  SONIDO_NOTA_C5, SONIDO_NOTA_G4, SONIDO_NOTA_E4, //45
  SONIDO_NOTA_A4, SONIDO_NOTA_B4, SONIDO_NOTA_A4, SONIDO_NOTA_GS4, SONIDO_NOTA_AS4, SONIDO_NOTA_GS4,
  SONIDO_NOTA_G4, SONIDO_NOTA_D4, SONIDO_NOTA_E4, SONIDO_NOTA_FIN

};

const int8_t mario_theme_duration[] = {

  8, 8, 8, 8, 8, 8, 8, //1
  4, 4, 8, 4,
  -4, 8, 4, -4, // 3
  4, 4, 8, 4,
  -8, -8, -8, 4, 8, 8,
  8, 4,8, 8, -4,
  -4, 8, 4, -4, // repeats from 3
  4, 4, 8, 4,
  -8, -8, -8, 4, 8, 8,
  8, 4,8, 8, -4,


  4, 8, 8, 8, 4, 8,//7
  8, 8, 8, 8, 8, 8, 8, 8,
  4, 4, 8, -4,
  2, 2,

  4, 8, 8, 8, 4, 8,//repeats from 7
  8, 8, 8, 8, 8, 8, 8, 8,
  4, 4, 8, -4,
  2, 2,

  8, 4, 8, 8, 8, 4,//11
  8, 4, 8, 2,

  8, 4, 8, 8, 8, 8, 8,//13
  1,
  8, 4, 8, 8, 8, 4,
  8, 4, 8, 2,
  8, 8, 8, 8, 8, 8, 4,
  4, 4, 4, 4,
  -4, 8, 4, -4, // 19

  4, 4, 8, 4,
  -8, -8, -8, 4, 8, 8,
  8, 4, 8, 8, -4,

  -4, 8, 4, -4, // repeats from 19
  4, 4, 8, 4,
  -8, -8, -8, 4, 8, 8,
  8, 4, 8, 8, -4,

  8, 4, 8, 4, 4,//23
  8, 4, 8, 2,
  -8, -8, -8, -8, -8, -8,

  8, 4, 8, 2, //26
  8, 4, 8, 4, 4,
  8, 4, 8, 2,
  8, 4, 8, -8, -8, -8,
  8, 4, 8, 2,

  8, 4, 8, 4, 4,//repeats from 23
  8, 4, 8, 2,
  -8, -8, -8, -8, -8, -8,

  8, 4, 8, 2, //26
  8, 4, 8, 4, 4,
  8, 4, 8, 2,
  8, 4, 8, -8, -8, -8,
  8, 4, 8, 2,
  8, 4, 8, 8, 8, 8, 8,
  1,

  8, 4, 8, 8, 8, 4, //33
  8, 4, 8, 2,
  8, 8, 8, 8, 8, 8, 4,
  4, 4, 4, 4,
  8, 4, 8, 4, 4,
  8, 4, 8, 2,
  -8, -8, -8, -8, -8, -8,

  8, 4, 8, 2, //40
  8, 4, 8, 4, 4,
  8, 4, 8, 2,
  8, 4, 8, -8, -8, -8,
  8, 4, 8, 2,

  //game over sound
  -4, -4, 4, //45
  -8, -8, -8, -8, -8, -8,
  8, 8, -2, 0

};

const sonido_melodia_t mario_theme = {
  .tempo = 200,
  .numero_notas = sizeof(mario_theme_notes) / sizeof(mario_theme_notes[0]),
  .ptr_notas = mario_theme_notes,
  .ptr_duracion_nota = mario_theme_duration
};

#endif  // SONIDO_MARIO_H