/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_flexio_mculcd.h"
#include "fsl_gpio.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_lpi2c.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define FLEXIO0_PERIPHERAL FLEXIO0
/* Definition of the clock source frequency */
#define FLEXIO0_CLK_FREQ 96000000UL
/* GPIO CS pin peripheral */
#define FLEXIO0_GPIO_PERIPHERAL_CSPIN GPIO2
/* GPIO CS pin number */
#define FLEXIO0_GPIO_CSPIN 19UL
/* GPIO RS pin peripheral */
#define FLEXIO0_GPIO_PERIPHERAL_RSPIN GPIO2
/* GPIO RS pin number */
#define FLEXIO0_GPIO_RSPIN 17UL
/* Definition of peripheral ID */
#define LPUART0_PERIPHERAL LPUART0
/* Definition of the clock source frequency */
#define LPUART0_CLOCK_SOURCE 12000000UL
/* BOARD_InitPeripherals defines for LPI2C2 */
/* Definition of peripheral ID */
#define LPI2C2_PERIPHERAL LPI2C2
/* Definition of clock source */
#define LPI2C2_CLOCK_FREQ 12000000UL
/* Transfer buffer size */
#define LPI2C2_MASTER_BUFFER_SIZE 1
/* Definition of follower address */
#define LPI2C2_MASTER_SLAVE_ADDRESS 0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
/* FlexIO peripheral configuration */
extern FLEXIO_MCULCD_Type FLEXIO0_peripheralConfig;
/* FlexIO MCULCD configuration */
extern flexio_mculcd_config_t FLEXIO0_config;
extern const lpuart_config_t LPUART0_config;
extern const lpi2c_master_config_t LPI2C2_masterConfig;
extern lpi2c_master_transfer_t LPI2C2_masterTransfer;
extern uint8_t LPI2C2_masterBuffer[LPI2C2_MASTER_BUFFER_SIZE];
extern lpi2c_master_handle_t LPI2C2_masterHandle;

/***********************************************************************************************************************
 * Global functions
 **********************************************************************************************************************/
/* GPIO CS pin set function */
void FLEXIO0_setCSPin(bool set);
/* GPIO RS pin set function */
void FLEXIO0_setRSPin(bool set);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
